### ISSUE TITLE
Update documentation for Barong interaction with client app

### ISSUE THREAD

**Issue by gfedorenko** [rubykube/barong#177]

**Comment by MaxSmile** [comment]
Say us something about config/database.yml  in the documentation, thanks!

```
~/barong$ bundle exec rake db:create db:migrate
rake aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/home/deploy/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/application/configuration.rb:139:in `database_configuration'
/home/deploy/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/railtie.rb:34:in `block (3 levels) in <class:Railtie>'
/home/deploy/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Could not load database configuration. No such file - ["config/database.yml"]
/home/deploy/.rvm/gems/ruby-2.4.2/gems/railties-5.1.4/lib/rails/application/configuration.rb:139:in `database_configuration'
/home/deploy/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/railtie.rb:34:in `block (3 levels) in <class:Railtie>'
/home/deploy/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
```

**Comment by ashanaakh** [comment]
Hi @MaxSmile!

Please, create new issue related to your question.

P.S. You should configure your local mysql DB, here is [example](https://github.com/rubykube/barong/blob/master/config/database.yml.example) configuration .
