### ISSUE TITLE
Username input throws exception

### ISSUE THREAD

**Issue by umaimehm** [rubykube/barong#252]
Everything was working fine, then I pulled code from github 2 days ago and first login seems to crash.
On Barong, after inoutting admin username, i get the following error:

TypeError in SessionsController#confirm
no implicit conversion of nil into String

Code with exception:
# Check if OTP key already exists for given uid
      def exist?(uid)
        Vault.logical.read("totp/keys/#{uid}").present?     # this line is the cause

The stacktrace is :
lib/vault/totp.rb:19:in `exist?'
app/controllers/sessions_controller.rb:27:in `otp_enabled?'
app/controllers/sessions_controller.rb:15:in `confirm'

**Comment by gfedorenko** [comment]
Hello @umaimehm

You need to set up vault for Barong.
You can find prerequisites and configuration info at [docs/configuration/2fa.md](https://github.com/rubykube/barong/blob/master/docs/configuration/2fa.md)

**Comment by umaimehm** [comment]
thanks @gfedorenko .

I have been stuck on this guide since the last 3 days. 
Since I have never worked with Vault before, I have a lot of confusions,

Info: Barong is run on a docker image and running on my host O.S, Ubuntu

1. I am assuming that vault should be installed on the local O.S (or any other server) but not on the docker image. Is that right ?

2. I installed Vault on my ubuntu and enabled 2fa
3. The guide tells to export the environment variables of Vault ( I am assuming i should export them in barong image, right ?)

export VAULT_ADDR=http://your-vault-url.com
export VAULT_TOKEN=12345-vault-t0k3n-54321

4. Restarted Barong, but im getting the same error as before.

5. I also tried to follow the guide  barong/docs/getting-started.md
but got numerous errors ont he configuration.
How should this vault be setup ? Is there any easier guide which can be followed ?

**Comment by gfedorenko** [comment]
@umaimehm 

You should get your vault server up by ``` vault server -dev ```` and don't terminate it.
You can see your vault address and root token.

Now try following next steps:
``` export VAULT_ADDR='your-vault-addr' ```
``` vault auth your-vault-root-token ```
``` vault secrets enable totp ```

Now export both VAULT_ADDR and VAULT_TOKEN and restart Barong server

**Comment by umaimehm** [comment]
okey so i did what you adviced,

vault server -dev  (OK and running )
export VAULT_ADDR='http://127.0.0.1:8200'
vault login (gives 4b2471ba-4f74-3690-313a-3c310887e1a6)
vault secrets enable totp  (OK)

Mae sure the variables are exposed to barong container:

docker-compose run --rm barong "echo $VAULT_TOKEN"
>>4b2471ba-4f74-3690-313a-3c310887e1a6
docker-compose run --rm barong "echo $VAULT_ADDR"
>> http://127.0.0.1:8200

restarted Barong server

I give username and press login, same error.
null pinter on Vault.

What am i doing wrong here ? I read up on vault guide and what you told me is exactly thats mentioned there.
I got a new virtual image and pulled the code to start from scratch. But the same issue persists.

**Comment by umaimehm** [comment]
The null exception is on totp.
Do I need to generate a key ?
In the configuration info at docs/configuration/2fa.md it shows, 

$ vault login
$ vault write totp/keys/IDMYAWESOMEID \
    generate=true                     \
    issuer=Barong                     \
    account_name=me@example.com

By getting info from seeds.yml fie, I ran the following command,
vault write totp/keys/a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4 generate=true  issuer=Barong account_name=admin@barong.io

since in seeds.yml:

admin:
  email:          "admin@barong.io"
applications:
  - name:         "Local Peatio"
    redirect_uri: "http://localhost:8000/auth/barong/callback"
    uid:          "a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4"
    secret:       "ab80e2c843861c4d23e63f5472cd1c9ee6f55e388863e21f22b03a9093977f29"
    skipauth:     true

**Comment by umaimehm** [comment]
it seems other users are also facing this issue.
@gfedorenko do you have any suggestions ? Would really appreciate some help.

**Comment by mod** [comment]
@dkkoval barong should work without 2FA and not fail at this stage
2FA only work if Vault is present and we need to display it on the UI, "2FA is disabled"

**Comment by umaimehm** [comment]
@mod thats a good point.
My whole setup with Barong was working until 2 weeks ago. I then updated the code from repo and thats where the problem started.

**Comment by harssh** [comment]
M stuck here too .. Any solution yet ...
<img width="1024" alt="screen shot 2018-03-23 at 8 29 31 pm" src="https://user-images.githubusercontent.com/2812994/37858853-f5db5006-2ed8-11e8-95cc-de2600e51492.png">

**Comment by top1st** [comment]
@gfedorenko Please give us solution.

**Comment by ridiks10** [comment]
I fixed the problem edit file sessions_controller.rb 

from code:
> def otp_enabled?
>     uid = find_uid_by_params_email
>     return false unless uid.present?
>     Vault::TOTP.exist?(uid)
> end

to code:
> def otp_enabled?
>     return false
> end

**Comment by yyoruk** [comment]
You won't be able to connect vault IP from docker container. First start a vault server as a container;

`docker run --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=349f338d-b7e1-d889-1c72-fe14128b5bd9' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' vault`

Then connect to your workbench network;

`docker network connect workbench_default workbench_vault_1`

Also add VAULT configuration to docker-compose.yml under barong section;

`VAULT_ADDR: http://workbench_vault_1:8200`
`VAULT_TOKEN: 349f338d-b7e1-d889-1c72-fe14128b5bd9`
