### ISSUE TITLE
Unable to sign in/sign up

### ISSUE THREAD

**Issue by vshatravenko** [rubykube/barong#266]
Version of Barong: 1.08-1.0.12
Whenever a user tries to sign up or sign in on the app, he gets an error screen with the following error in the logs:
```
I, [2018-03-17T00:19:42.540398 #1]  INFO -- : [51b07eb9-8202-4658-a4bd-7b1f0b4c6b93] Completed 401 Unauthorized in 3ms (ActiveRecord: 0.5ms)
F, [2018-03-17T00:19:42.541022 #1] FATAL -- : [51b07eb9-8202-4658-a4bd-7b1f0b4c6b93]   
F, [2018-03-17T00:19:42.541074 #1] FATAL -- : [51b07eb9-8202-4658-a4bd-7b1f0b4c6b93] TypeError (no implicit conversion of nil into String):
F, [2018-03-17T00:19:42.541149 #1] FATAL -- : [51b07eb9-8202-4658-a4bd-7b1f0b4c6b93]   
F, [2018-03-17T00:19:42.541223 #1] FATAL -- : [51b07eb9-8202-4658-a4bd-7b1f0b4c6b93] lib/vault/totp.rb:19:in `exist?'
[51b07eb9-8202-4658-a4bd-7b1f0b4c6b93] app/controllers/sessions_controller.rb:27:in `otp_enabled?'
[51b07eb9-8202-4658-a4bd-7b1f0b4c6b93] app/controllers/sessions_controller.rb:15:in `confirm'
```
The deployment on which the issue was encountered is running on a clean database, disabling/enabling Vault in the configs didn't affect the issue at all.

**Comment by umaimehm** [comment]
similar issue documented here: https://github.com/rubykube/barong/issues/252
