### ISSUE TITLE
Vault 404 when enabling 2FA

### ISSUE THREAD

**Issue by calj** [rubykube/barong#355]
```
[barong-barong-7d9574db95-72nvk] F, [2018-04-16T14:47:58.198982 #1] FATAL -- : [32f65425-1b8a-4bcb-9786-8b09787930f7] 
[barong-barong-7d9574db95-72nvk] F, [2018-04-16T14:47:58.199147 #1] FATAL -- : [32f65425-1b8a-4bcb-9786-8b09787930f7] Vault::HTTPClientError (The Vault server at `http://vault-vault' responded with a 404. 
[barong-barong-7d9574db95-72nvk] Any additional information the server supplied is shown below: 
[barong-barong-7d9574db95-72nvk]  
[barong-barong-7d9574db95-72nvk] * no handler for route 'totp/keys/IDB21538E3A8' 
[barong-barong-7d9574db95-72nvk]  
[barong-barong-7d9574db95-72nvk] Please refer to the documentation for help. 
[barong-barong-7d9574db95-72nvk] ): 
[barong-barong-7d9574db95-72nvk] F, [2018-04-16T14:47:58.199205 #1] FATAL -- : [32f65425-1b8a-4bcb-9786-8b09787930f7] 
[barong-barong-7d9574db95-72nvk] F, [2018-04-16T14:47:58.199278 #1] FATAL -- : [32f65425-1b8a-4bcb-9786-8b09787930f7] lib/vault/totp.rb:29:in `create' 
[barong-barong-7d9574db95-72nvk] [32f65425-1b8a-4bcb-9786-8b09787930f7] lib/vault/totp.rb:14:in `safe_create' 
[barong-barong-7d9574db95-72nvk] [32f65425-1b8a-4bcb-9786-8b09787930f7] app/controllers/security_controller.rb:10:in `enable' 
```

**Comment by maksim-litvinov** [comment]
Vault TOTP is not enabled. Command to enable `vault secrets enable totp`
