### ISSUE TITLE
Otp sign request unexpected behavior 

### ISSUE THREAD

**Issue by ysv** [rubykube/barong#545]
```
D, [2018-06-19T18:29:16.193554 #9] DEBUG -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] Vault TOTP key "totp/keys/IDFEF1EDCBA2" exists? true
D, [2018-06-19T18:29:16.193652 #9] DEBUG -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] Validate TOTP code: key totp/code/IDFEF1EDCBA2, code: 12345
F, [2018-06-19T18:29:16.195642 #9] FATAL -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8]
F, [2018-06-19T18:29:16.195741 #9] FATAL -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] Vault::HTTPClientError (The Vault server at `http://vault-vault' responded with a 400.
Any additional information the server supplied is shown below:

  * code already used; wait until the next time period

Please refer to the documentation for help.
):
F, [2018-06-19T18:29:16.195821 #9] FATAL -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8]
F, [2018-06-19T18:29:16.195891 #9] FATAL -- : [7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] lib/vault/totp.rb:72:in `write_data'
[7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] lib/vault/totp.rb:43:in `validate?'
[7a2e1fb9-1c99-4770-9d70-5325c54a7ca8] app/api/management_api/v1/otp.rb:31:in `block (2 levels) in <class:OTP>'
I, [2018-06-19T18:29:22.342375 #9]  INFO -- : [3e8f1ea0-a273-4ed6-9687-cb5fb7422a7e] Started GET "/" for 10.24.1.1 at 2018-06-19 18:29:22 +0000
I, [2018-06-19T18:29:22.343164 #9]  INFO -- : [3e8f1ea0-a273-4ed6-9687-cb5fb7422a7e] Processing by IndexController#index as HTML
I, [2018-06-19T18:29:22.343889 #9]  INFO -- : [3e8f1ea0-a273-4ed6-9687-cb5fb7422a7e] Redirected to http://10.24.1.71:8080/accounts/sign_in
I, [2018-06-19T18:29:22.344028 #9]  INFO -- : [3e8f1ea0-a273-4ed6-9687-cb5fb7422a7e] Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
I, [2018-06-19T18:29:22.345196 #9]  INFO -- : [b0be3408-31c6-455e-81f3-aef7af64aa79] Started GET "/accounts/sign_in" for 10.24.1.1 at 2018-06-19 18:29:22 +0000
I, [2018-06-19T18:29:22.345653 #9]  INFO -- : [b0be3408-31c6-455e-81f3-aef7af64aa79] Processing by SessionsController#new as HTML
I, [2018-06-19T18:29:22.346638 #9]  INFO -- : [b0be3408-31c6-455e-81f3-aef7af64aa79]   Rendering devise/sessions/new.html.erb within layouts/devise
```

**Comment by maksim-litvinov** [comment]
Fixed in 1.8.26
